version: '3'

networks:
  neon-net:

services:
  neon-dash:
    container_name: neon-dash
    image: nginx:alpine
    ports: 
      - 4199:80
    networks:
      neon-net:
    volumes:
      - ./dist:/var/www:ro
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources/config.yaml:/var/www/app/config/config.yaml
  # neon-dash-dev:
  #   container_name: neon-dash-dev
  #   image: nginx:alpine
  #   ports: 
  #     - 5199:81
  #   networks:
  #     neon-net:
  #   volumes:
  #     - ./dist:/var/www:ro
  #     - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./resources/config.yaml:/var/www/app/config/config.yaml
  analysis-ui:
    container_name: analysis-ui
    image: analysis-ui
    volumes:
      - ./configs/prod/config.js:/usr/src/app/public/js/config.js
    ports: 
      - 3000:3000
    depends_on:
      - neon-es
      - node-server
    networks:
      - neon-net
  # analysis-ui-dev:
  #   container_name: analysis-ui-dev
  #   image: analysis-ui
  #   volumes:
  #     - ./configs/prod/config.js:/usr/src/app/public/js/config.js
  #   ports: 
  #     - 3100:3100
  #   depends_on:
  #     - neon-es
  #     - node-server
  #   networks:
  #     - neon-net
  node-server:
    container_name: node-graphql
    image: node-graphql
    environment:
      - ES_HOST=elasticsearch
      - NODE_PORT=9100
      - ELASTIC_URL=http://neon-es:9200
    ports: 
      - 9100:9100
    expose:
      - 9100
    depends_on:
      - neon-es
      - kibana
      - neon-server
    networks:
      - neon-net
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.7.2
    environment:
      - "ELASTICSEARCH_URL=http://neon-es:9200"
    ports:
      - 5601:5601
    networks:
      - neon-net
    depends_on:
      - neon-es
  neon-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: neon-es
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200      
    networks:
      neon-net:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 1s
      retries: 30
  neon-server:
    environment:
      STATE_DIRECTORY: /config
      SERVER_PORT: 80
    volumes:
      - ./resources:/config
    image: com.ncc.neon/server:latest
    container_name: neon-server
    expose:
      - 80
    networks:
      neon-net:
  # neon-server-dev:
  #   environment:
  #     STATE_DIRECTORY: /config
  #     SERVER_PORT: 81
  #   volumes:
  #     - ./resources:/config
  #   image: com.ncc.neon/server:latest
  #   container_name: neon-server
  #   expose:
  #     - 81
  #   networks:
  #     neon-net:
  